// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/notifications.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_proto_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerificationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerificationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Attachment) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type TicketSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerName     string                 `protobuf:"bytes,1,opt,name=buyer_name,json=buyerName,proto3" json:"buyer_name,omitempty"`
	BuyerEmail    string                 `protobuf:"bytes,2,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketSendRequest) Reset() {
	*x = TicketSendRequest{}
	mi := &file_proto_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketSendRequest) ProtoMessage() {}

func (x *TicketSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketSendRequest.ProtoReflect.Descriptor instead.
func (*TicketSendRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *TicketSendRequest) GetBuyerName() string {
	if x != nil {
		return x.BuyerName
	}
	return ""
}

func (x *TicketSendRequest) GetBuyerEmail() string {
	if x != nil {
		return x.BuyerEmail
	}
	return ""
}

func (x *TicketSendRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TicketSendRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_proto_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *EmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notifications_proto protoreflect.FileDescriptor

const file_proto_notifications_proto_rawDesc = "" +
	"\n" +
	"\x19proto/notifications.proto\x12\rnotifications\"v\n" +
	"\x13VerificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"H\n" +
	"\n" +
	"Attachment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\xaf\x01\n" +
	"\x11TicketSendRequest\x12\x1d\n" +
	"\n" +
	"buyer_name\x18\x01 \x01(\tR\tbuyerName\x12\x1f\n" +
	"\vbuyer_email\x18\x02 \x01(\tR\n" +
	"buyerEmail\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12;\n" +
	"\vattachments\x18\x04 \x03(\v2\x19.notifications.AttachmentR\vattachments\"C\n" +
	"\rEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbc\x01\n" +
	"\fEmailService\x12Y\n" +
	"\x15SendVerificationEmail\x12\".notifications.VerificationRequest\x1a\x1c.notifications.EmailResponse\x12Q\n" +
	"\x0fSendTicketEmail\x12 .notifications.TicketSendRequest\x1a\x1c.notifications.EmailResponseB\x16Z\x14proto/notificationpbb\x06proto3"

var (
	file_proto_notifications_proto_rawDescOnce sync.Once
	file_proto_notifications_proto_rawDescData []byte
)

func file_proto_notifications_proto_rawDescGZIP() []byte {
	file_proto_notifications_proto_rawDescOnce.Do(func() {
		file_proto_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notifications_proto_rawDesc), len(file_proto_notifications_proto_rawDesc)))
	})
	return file_proto_notifications_proto_rawDescData
}

var file_proto_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_notifications_proto_goTypes = []any{
	(*VerificationRequest)(nil), // 0: notifications.VerificationRequest
	(*Attachment)(nil),          // 1: notifications.Attachment
	(*TicketSendRequest)(nil),   // 2: notifications.TicketSendRequest
	(*EmailResponse)(nil),       // 3: notifications.EmailResponse
}
var file_proto_notifications_proto_depIdxs = []int32{
	1, // 0: notifications.TicketSendRequest.attachments:type_name -> notifications.Attachment
	0, // 1: notifications.EmailService.SendVerificationEmail:input_type -> notifications.VerificationRequest
	2, // 2: notifications.EmailService.SendTicketEmail:input_type -> notifications.TicketSendRequest
	3, // 3: notifications.EmailService.SendVerificationEmail:output_type -> notifications.EmailResponse
	3, // 4: notifications.EmailService.SendTicketEmail:output_type -> notifications.EmailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_notifications_proto_init() }
func file_proto_notifications_proto_init() {
	if File_proto_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notifications_proto_rawDesc), len(file_proto_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notifications_proto_goTypes,
		DependencyIndexes: file_proto_notifications_proto_depIdxs,
		MessageInfos:      file_proto_notifications_proto_msgTypes,
	}.Build()
	File_proto_notifications_proto = out.File
	file_proto_notifications_proto_goTypes = nil
	file_proto_notifications_proto_depIdxs = nil
}
